"""Generate graphrag v3.x settings.yaml."""

from __future__ import annotations

import logging
from pathlib import Path

log = logging.getLogger("graphrag-backend")


def generate_settings(root: Path, llm: dict, entity_types: list[str]) -> str:
    """Build the full settings.yaml content as a string."""
    ak = llm["api_key"]
    base = llm["api_base"].rstrip("/")
    emb_base = (llm.get("emb_base") or llm["api_base"]).rstrip("/")
    et_str = ",".join(entity_types)

    return f"""### Auto-generated by GraphRAG Demo

completion_models:
  default_completion_model:
    model_provider: openai
    model: {llm["model"]}
    auth_method: api_key
    api_key: {ak}
    api_base: {base}
    retry:
      type: exponential_backoff

embedding_models:
  default_embedding_model:
    model_provider: openai
    model: {llm["emb_model"]}
    auth_method: api_key
    api_key: {ak}
    api_base: {emb_base}
    retry:
      type: exponential_backoff

input:
  type: text

chunking:
  type: tokens
  size: 1200
  overlap: 100
  encoding_model: o200k_base

input_storage:
  type: file
  base_dir: "input"

output_storage:
  type: file
  base_dir: "output"

reporting:
  type: file
  base_dir: "logs"

cache:
  type: json
  storage:
    type: file
    base_dir: "cache"

vector_store:
  type: lancedb
  db_uri: output/lancedb

embed_text:
  embedding_model_id: default_embedding_model
  batch_size: 10
  batch_max_tokens: 4096

extract_graph:
  completion_model_id: default_completion_model
  prompt: "prompts/extract_graph.txt"
  entity_types: [{et_str}]
  max_gleanings: 1

summarize_descriptions:
  completion_model_id: default_completion_model
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english

cluster_graph:
  max_cluster_size: 10

extract_claims:
  enabled: false
  completion_model_id: default_completion_model
  prompt: "prompts/extract_claims.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  completion_model_id: default_completion_model
  graph_prompt: "prompts/community_report_graph.txt"
  text_prompt: "prompts/community_report_text.txt"
  max_length: 2000
  max_input_length: 8000

snapshots:
  graphml: false
  embeddings: false

local_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  completion_model_id: default_completion_model
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/drift_search_system_prompt.txt"
  reduce_prompt: "prompts/drift_search_reduce_prompt.txt"

basic_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/basic_search_system_prompt.txt"
"""


def write_settings(root: Path, llm: dict, entity_types: list[str]) -> str:
    """Generate settings.yaml content and write it to <root>/settings.yaml.

    Returns the generated content string.
    """
    content = generate_settings(root, llm, entity_types)
    (root / "settings.yaml").write_text(content)
    log.info("Written settings.yaml to %s", root)
    return content
